removed bash version check

diff --git a/install b/install
--- a/install
+++ b/install
@@ -4,10 +4,10 @@ awesome_dir="$HOME/awesome"
 bin_dir="$HOME/bin"
 # version="0.1.1"
 
-if ((BASH_VERSINFO[0] < 4)); then
-    printf '%s\n' "Error: This requires Bash v4.0 or higher. You have version $BASH_VERSION." 1>&2
-    exit 2
-fi
+# if ((BASH_VERSINFO[0] < 4)); then
+#     printf '%s\n' "Error: This requires Bash v4.0 or higher. You have version $BASH_VERSION." 1>&2
+#     exit 2
+# fi
 
 fn_confirm() {
     local item=$1
